$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: carpricer-service
endpoint_name:
model: azureml:carpricer@latest
type: managed
instance_type: Standard_DS2_v2
instance_count: 1